AWSTemplateFormatVersion: '2010-09-09'
Description: "DNS configuration"

Parameters:
  ApiGatewayHostedZoneId:
    Description: DNS zone ID of the deployed API Gateway for the mobile API
    Type: String
    Default: Z19DQILCV0OWEC
  CloudfrontHostedZone:
    Default: Z2FDTNDATAQYW2
    Type: String
  ZoneName:
    Default: heart-of.me
    Description: "FQDN heart-of.me"
    Type: String
  DevMediaDistribution:
    Type: String
    Default: "d15gue09xfvm24.cloudfront.net"


Resources:
  Zone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: 'heart-of.me hosted zone'
      Name: !Ref ZoneName

  DevEmailValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Firebase email validation record
      HostedZoneId: !GetAtt Zone.Id
      Name: "firebase1._domainkey.dev.heart-of.me"
      ResourceRecords:
        - "mail-dev-heart--of-me.dkim1._domainkey.firebasemail.com."
      TTL: 14400
      Type: CNAME

  DevEmailValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Firebase email validation record
      HostedZoneId: !GetAtt Zone.Id
      Name: "firebase2._domainkey.dev.heart-of.me"
      ResourceRecords:
        - "mail-dev-heart--of-me.dkim2._domainkey.firebasemail.com."
      TTL: 14400
      Type: CNAME

  DevEmailValidationRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Firebase email validation record
      HostedZoneId: !GetAtt Zone.Id
      Name: "dev.heart-of.me"
      ResourceRecords:
        - "\"v=spf1 include:_spf.firebasemail.com ~all\""
        - "\"firebase=heart-of-yours-dev\""
      TTL: 14400
      Type: TXT

  DevMediaDistributionCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: 'Dev media CF distribution'
      HostedZoneId: !GetAtt Zone.Id
      Name: _a66f9b14b2fe79100de8da2794bbda3e.dev.media.heart-of.me.
      ResourceRecords:
        - _1d9796af82610f64321c6d4ffc014691.xlfgrmvvlj.acm-validations.aws.
      TTL: 14400
      Type: CNAME

  DevMediaDistributionRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: 'Dev media CF distribution'
      HostedZoneId: !GetAtt Zone.Id
      Name: "dev.media.heart-of.me"
      ResourceRecords:
        - !Ref DevMediaDistribution
      TTL: 14400
      Type: CNAME

