version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda-layers"
s3_bucket = "aws-sam-583168578067"
s3_prefix = "lambda-layers"
region = "ca-central-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = """
    Env=\"dev\"
"""
tags = """
    application=\"lambda-layers\"
    AppManagerCFNStackKey=\"lambda-layers\"
"""
