AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda Layers"

Resources:
  LayersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-lambda-layers"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FirebaseAdminLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: "firebase"
      Description: "Lambda Layer for firebase_admin library"
      Content:
        S3Bucket: !Ref LayersBucket
        S3Key: firebase_admin.zip
      CompatibleRuntimes:
        - python3.13

  FirebaseLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref FirebaseAdminLayer
      Principal: "*"

Outputs:
  FirebaseAdminLayerOutput:
    Description: "Firebase Admin Lambda Layer"
    Value: !Ref FirebaseAdminLayer
