AWSTemplateFormatVersion: "2010-09-09"
Description: "Heart API"
Transform: "AWS::Serverless-2016-10-31"


Globals:
  Function:
    Runtime: python3.13
    Handler: app.handler

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod

Mappings:
  Env:
    dev:
      LogRetention: 3 # days
    prod:
      LogRetention: 90 # days


Resources:
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "heart-api"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  AccountsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt Api.RootResourceId
      PathPart: "accounts"
      RestApiId: !Ref Api

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      FunctionName: "heart-api"
      Layers:
        - arn:aws:lambda:ca-central-1:583168578067:layer:firebase-admin-layer:1
      Role: !GetAtt LambdaExecutionRole.Arn

  ApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub  "/aws/lambda/${ApiFunction}"
      RetentionInDays: !FindInMap [ Env, !Ref Env, LogRetention ]

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ApiFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*"
        - Api: !Ref Api

  DeleteAccountMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: DELETE
      ResourceId:
        Ref: AccountsResource
      RestApiId: !Ref Api
      AuthorizationType: NONE
      OperationName: "delete-account"
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
            - "arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations"
            - Region: !Ref "AWS::Region"
              LambdaArn: !GetAtt ApiFunction.Arn

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - DeleteAccountMethod
    Properties:
      RestApiId: !Ref Api

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: "api"
      RestApiId: !Ref Api
      DeploymentId: !Ref Deployment

